{% set name = "radar-api" %}
{% set version = "0.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/radar_api-{{ version }}.tar.gz
  sha256: 0238a6008653b05af16e6716cd5991f0b91f5bec8b6915c9ef7d9dd45084b203

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - fsspec
    - s3fs
    - pyyaml
    - donfig
    - trollsift
    - numpy
    - pandas
    - tqdm

test:
  imports:
    - radar_api
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ghiggi/radar_api
  summary: Python software to retrieve weather radar data from cloud buckets
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ghiggi
